function plot_multB()

%% ===== Step 1: Read data =====
obs_tstar  = evalin('base','X_test_tstar');
obs_tminus = evalin('base','X_test_tminus');
obs_tplus  = evalin('base','X_test_tplus');

pred_tstar  = evalin('base','X_p_tstar');
pred_tminus = evalin('base','X_p_tminus');
pred_tplus  = evalin('base','X_p_tplus');

% remove unperturbed initial state
obs_tstar(:,1,:)  = [];
obs_tminus(:,1,:) = [];
obs_tplus(:,1,:)  = [];

%% ===== Step 2: Size check =====
[~,numPerturb_obs,~]  = size(obs_tstar);
[~,numPerturb_pred,~] = size(pred_tstar);

if numPerturb_obs ~= numPerturb_pred
    error('Observed and predicted perturbation numbers do not match.');
end

numPerturb = numPerturb_obs;

%% ===== Step 3: Compute mean curves =====
obsMean_tstar  = squeeze(mean(mean(obs_tstar,3),1));
obsMean_tminus = squeeze(mean(mean(obs_tminus,3),1));
obsMean_tplus  = squeeze(mean(mean(obs_tplus,3),1));

predMean_tstar  = squeeze(mean(mean(pred_tstar,3),1));
predMean_tminus = squeeze(mean(mean(pred_tminus,3),1));
predMean_tplus  = squeeze(mean(mean(pred_tplus,3),1));

xVals = linspace(0,1,numPerturb);

%% ===== Step 4: Figure (same as plot_multi) =====
fig = figure('Color','w');

fig.Units = 'centimeters';
fig.Position = [2 2 16 16];

fig.PaperUnits = 'centimeters';
fig.PaperPosition = [0 0 12 12];
fig.PaperSize = [12 12];

ax = axes(fig);
hold(ax,'on');

%% ===== Step 5: Axis style (same as plot_multi) =====
set(ax,...
    'FontSize',25,...
    'FontName','Times New Roman',...
    'LineWidth',2.0,...
    'TickDir','in',...
    'TickLength',[0.01 0.01],...
    'Layer','top',...
    'Box','on');

ax.Units = 'normalized';
ax.Position = [0.12 0.12 0.83 0.83];

%% ===== Step 6: Colors =====
blue = [0.00 0.45 0.74];
red  = [0.75 0.00 0.00];

%% ===== Step 7: marker positions =====
markerX = linspace(xVals(1), xVals(end), 6);
markerIdx = zeros(size(markerX));

for ii = 1:numel(markerX)
    [~, markerIdx(ii)] = min(abs(xVals-markerX(ii)));
end

markerIdx = unique(markerIdx);

%% ===== Step 8: Plot curves =====

% ----- t* solid -----
% ----- t* solid -----
h1 = plot(ax,xVals,obsMean_tstar,'-',...
    'Color',blue,...
    'LineWidth',2.35,...
    'Marker','o',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',blue,...
    'MarkerEdgeColor','none');

h2 = plot(ax,xVals,predMean_tstar,'-',...
    'Color',red,...
    'LineWidth',2.35,...
    'Marker','^',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',red,...
    'MarkerEdgeColor','none');

% ----- t+ dashed -----
h3 = plot(ax,xVals,obsMean_tplus,'--',...
    'Color',blue,...
    'LineWidth',2.35,...
    'Marker','o',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',blue,...
    'MarkerEdgeColor','none');

h4 = plot(ax,xVals,predMean_tplus,'--',...
    'Color',red,...
    'LineWidth',2.35,...
    'Marker','^',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',red,...
    'MarkerEdgeColor','none');

% ----- t- dotted -----
h5 = plot(ax,xVals,obsMean_tminus,':',...
    'Color',blue,...
    'LineWidth',2.5,...
    'Marker','o',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',blue,...
    'MarkerEdgeColor','none');

h6 = plot(ax,xVals,predMean_tminus,':',...
    'Color',red,...
    'LineWidth',2.5,...
    'Marker','^',...
    'MarkerIndices',markerIdx,...
    'MarkerSize',6,...
    'MarkerFaceColor',red,...
    'MarkerEdgeColor','none');
%% ===== Step 9: Axis limits =====
xlim(ax,[0 1])
ax.XTick = linspace(0,1,3);

%ylim(ax,[0 0.6])
%ax.YTick = linspace(0,0.6,3);

ylim(ax,[0 10])
ax.YTick = linspace(0,10,3);

%ylim(ax,[0 1])
%ax.YTick = linspace(0,1,3);
%% ===== Step 10: Legend (same font size as plot_multi) =====
lg = legend(ax,[h1 h2 h3 h4 h5 h6],...
    {'Observed results, $t^{*}$',...
     'Predicted results, $t^{*}$',...
     'Observed results, $t^{+}$',...
     'Predicted results, $t^{+}$',...
     'Observed results, $t^{-}$',...
     'Predicted results, $t^{-}$'},...
    'Location','northeast',...
    'FontSize',13,...
    'FontName','Times New Roman',...
    'Interpreter','latex',...
    'Box','off');
lg.ItemTokenSize = [26 10];
legend off;

hold(ax,'off');

end